app/__init__.py
import os
import secrets
from flask import Flask


def create_app():
    # create and configure the app
    app = Flask(__name__, static_folder="", instance_path="/app")

    app.config["SECRET_KEY"] = "dev"
    app.config["DATABASE"] = "app/instance/dev.db"

    # register database
    from app.db import init_app
    init_app(app) 

    # register blueprints
    from app.routes import home
    app.register_blueprint(home)

    return app

app/routes.py
from flask import Blueprint, url_for, render_template
from app.db import get_db
from app.analytics import *
import json

home = Blueprint('home', __name__, template_folder='templates')

@home.route("/")
def index():

    db = get_db()
    cur = db.cursor()

    schools = cur.execute("""
    SELECT name FROM school
    """).fetchall()

    return render_template("index.html", schools=schools)




@home.route("/school/<school>")
def school(school):
    
    db = get_db()
    cur = db.cursor()


    school = cur.execute("""
    SELECT * FROM school
    WHERE name = ?
    """, (school, )).fetchone()


    athletes = cur.execute("""
                   SELECT * FROM athlete
                   WHERE school_id = ?
    """, (school["id"], )).fetchall()

    sport_ids = tuple(set([athlete["sport_id"] for athlete in athletes]))
    sport_placeholders = str(["?" for _ in  range(len(sport_ids))]).replace("[", "(").replace("]", ")").replace("'", "")

    sports = cur.execute(f"""
                 SELECT * FROM sport
                 WHERE id in {sport_placeholders} 
    """, sport_ids).fetchall()

    athlete_ids = tuple([athlete["id"] for athlete in athletes])
    img_placeholders = str(["?" for _ in  range(len(athlete_ids))]).replace("[", "(").replace("]", ")").replace("'", "")

    images = cur.execute(f"""
             SELECT * FROM image
             WHERE athlete_id IN {img_placeholders}
    """, athlete_ids).fetchall()

    
    for athlete in athletes:

        sport_id_index = 0
        for i, sport in enumerate(sports):
            if sport["id"] == athlete["sport_id"]:
                sport_id_index = i
                break

        athlete["sport"] = sports[sport_id_index]
        athlete["images"] = [img for img in images if img["athlete_id"] == athlete["id"]]


    return render_template("school.html", school=school, athletes=athletes)



@home.route("/database/update")
def update_database():

    db = get_db()
    cur = db.cursor()

    schools = get_school_json_data(path="app/data/all_schools_data.json")

    # Insert schools and sports
    for name, school_data in schools.items():
        cur.execute("""
            INSERT OR IGNORE INTO school (name)
            VALUES(?)
        """, (name, ))

        for sport, athletes in school_data.items():
            cur.execute("""
                INSERT OR IGNORE INTO sport (name)
                VALUES(?)
            """, (sport, ))


    # Insert athletes
    for school_name, school_data in schools.items():

        school_id = cur.execute("""
                        SELECT name, id FROM school
                        WHERE name = ?
        """, (school_name, )).fetchone()["id"]
 

        for sport, athletes in school_data.items():

            sport_id = cur.execute("""
                           SELECT name, id FROM sport
                           WHERE name = ?
            """, (sport, )).fetchone()["id"]

            for athlete in athletes:

                misc = json.dumps({k:v for k, v in athlete.items() if k not in ["id", "name", "gender", "school_url", "sport", "images"]})

                if athlete["gender"] not in ["M", "F"]:
                    athlete["gender"] = "M"

                cur.execute("""
                    INSERT INTO athlete (athlete_key, name, gender, misc, sport_id, school_id)
                    VALUES(?, ?, ?, ?, ?, ?)
                """, (athlete["id"], athlete["name"], athlete["gender"].strip().replace("\"", ""), misc, sport_id, school_id))



    # Insert images
    for name, school_data in schools.items():
        for sport, athletes in school_data.items():
            for athlete in athletes:

                athlete_id = cur.execute("""
                                 SELECT id, name FROM athlete
                                 WHERE name = ?
                """, (athlete["name"], )).fetchone()["id"]

                for image in athlete["images"]:
                    cur.execute("""
                        INSERT INTO image (url, athlete_id)
                        VALUES(?, ?)
                    """, (image, athlete_id))

                    


    db.commit()
    
    return "Database updated!"


@home.route("/database/delete")
def delete_database():

    db = get_db()
    cur = db.cursor()

    for table in ["school", "sport", "athlete", "image"]:
        cur.execute(f"DELETE FROM {table}")

    db.commit()

    return "Database Deleted"



@home.route("/test")
def test():
    return render_template("test.html")


@home.route("/message", methods=["GET"]) 
def message():
    
    db = get_db()
    cur = db.cursor()
       
    print("\n\n\n")
    print(cur.execute("SELECT * FROM image").fetchall())
    print("\n\n\n")

    return "Success!"

app/templates/base.html
<!doctype html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- HTMX -->
  <script src="https://unpkg.com/htmx.org@2.0.3"></script>

  <!-- Tailwind -->
  <script src="https://cdn.tailwindcss.com"></script>

  <!-- Alpine.js -->
  <script src="//unpkg.com/alpinejs" defer></script>


</head>

<html class="font-light h-full">

  <body class="h-full" hx-boost="true">

    <div class="flex flex-col justify-center items-center space-y-4">

      <p class="text-3xl font-bold">
        Canadian Varsity Analytics Web App
      <p>

      <hr class="w-full border-black">

      {% block body %}
      {% endblock %}

    </div>

  </body>

</html>

app/templates/index.html
{% extends "base.html" %}


{% block body %}

  <div class="flex flex-col justify-center items-center space-y-4">

    <p class="text-2xl font-medium">
      Choose a school
    <p>

    <div class="grid grid-cols-4 gap-4">
      {% for school in schools %}
        <a
          class="p-2 border-2 bg-neutral-300 border-neutral-500 rounded-md"
          href="{{ url_for('home.school', school=school.name) }}"
          >
          {{ school.name }}
        </a>
      {% endfor %}
    </div>

  <hr class="w-full py-2 border-black">

    <div class="flex flex-col">

      <div class="flex flex-row space-x-2">

        <!-- <button  -->
        <!--       class="p-2 border-2 bg-neutral-300 border-neutral-500 rounded-md" -->
        <!--       hx-get="/database/update" -->
        <!--       hx-swap="innerHMTL" -->
        <!--       hx-target="#database-updated" -->
        <!--   > -->
        <!--   Update Database -->
        <!-- </button> -->
        <!-- <button  -->
        <!--       class="p-2 border-2 bg-neutral-300 border-neutral-500 rounded-md" -->
        <!--       hx-get="/database/delete" -->
        <!--       hx-swap="innerHMTL" -->
        <!--       hx-target="#database-deleted" -->
        <!--   > -->
        <!--   Delete Database -->
        <!-- </button> -->
      </div>

      <div id="database-updated"></div>
      <div id="database-deleted"></div>

    </div>

  </div>



{% endblock %}

app/templates/school.html
{% extends "base.html" %}


{% block body %}


  <div class="flex flex-col">

    <p class="text-2xl font-medium">
    {{ school.name }} - All Athletes
    <p>

    <div class="grid grid-cols-8 gap-2">
      {% for athlete in athletes %}
        <div class="flex flex-col space-y-2">

          {% if athlete.images|length > 0 %}
            <img src="{{ athlete.images[0].url }}" width="250" height="500">
          {% else %}
            <span>No Image</span>
          {% endif %}
          <p class="flex flex-col">
            <span>{{ athlete.name }} - {{ athlete.sport.name }}</span>
          </p>

        </div>
      {% endfor %}
    </div>


  </div>


{% endblock %}

app/templates/test.html
{% extends "base.html" %}


{% block body %}

  <div class="flex flex-col justify-center items-center">
    <button class="w-16 h-12 border-2 rounded-md bg-neutral-200"
    hx-get="/message"
    hx-target="#target"
    hx-swap="innerHTML"
    >
      Click
    </button>
    <div id="target">
    </div>
  </div>

{% endblock %}